// <auto-generated />
using System;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(DbContextDiego))]
    partial class DbContextDiegoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.ConteoResponseDTO", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaConsultada")
                        .HasColumnType("datetime2");

                    b.Property<string>("hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sentido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TBL_Conteo");
                });

            modelBuilder.Entity("Domain.Models.RecaudoResponseDTO", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaConsultada")
                        .HasColumnType("datetime2");

                    b.Property<string>("hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sentido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("valorTabulado")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("TBL_Recaudo");
                });
#pragma warning restore 612, 618
        }
    }
}
